name: Node CI

on:
- pull_request
- push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install node_modules
      run: |
        npm install
    - name: Run tests
      run: |
        npm test:nowatch
      env:
        NODE_ENV: test

    - name: Build
      run: |
        npm run build
